#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
