#!/usr/bin/env bash
# Install nginx on your web-01

sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
