#!/usr/bin/env bash
# install and configure HAproxy on server to serve as load balancer

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9
apt-get update
apt-get -y install haproxy=2.9.\*

echo -e 'ENABLED=1' >> /etc/default/haproxy

echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 506736-web-01 35.174.208.250
\tserver 506736-web-02 18.209.179.190
' >> /etc/haproxy/haproxy.cfg
service haproxy restart
