#!/usr/bin/env bash
# Checking what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
rm /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
